name: 🔗 GHA Android Only
on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

env:
  GODOT_CIPHER_KEY: ${{ secrets.GODOT_CIPHER_KEY }}

jobs:
  # 静态检查（可选，想更快可以删掉）
  static-checks:
    if: ${{ !vars.DISABLE_GODOT_CI || github.run_attempt > 1 || github.event_name == 'workflow_dispatch' }}
    name: 📊 Static checks
    uses: ./.github/workflows/static_checks.yml

  android-build:
    name: 🤖 Android
    needs: static-checks
    if: needs.static-checks.outputs.sources-changed == 'true' || github.event_name != 'pull_request'
    uses: ./.github/workflows/android_builds.yml
    secrets:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
